version: '3.8'

services:
  db:
    image: mysql:8
    container_name: sistema_horarios_mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - sistema_horarios_network
    ports:
      - "127.0.0.1:3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: sistema_horarios_django
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema_horarios_network
    command: >
      sh -c "gunicorn --bind 0.0.0.0:3000 --workers 4 --timeout 120 --max-requests 1000 --max-requests-jitter 100 core.wsgi:application"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000/"]
      timeout: 30s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: sistema_horarios_nginx
    restart: always
    ports:
      - "127.0.0.1:80:80"
      # - "127.0.0.1:443:443"       Puerto comentado hasta configurar SSL
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      # - ./ssl:/etc/nginx/ssl:ro       Certificados SSL, comentado hasta configurar SSL
    depends_on:
      web:
        condition: service_healthy
    networks:
      - sistema_horarios_network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/"]
      timeout: 30s
      retries: 3

volumes:
  mysql_data:
  static_volume:

networks:
  sistema_horarios_network:
    driver: bridge