# Generated by Django 5.2.6 on 2025-09-19 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Practicantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NivelHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='Habilidades.habilidad')),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_habilidad', to='Practicantes.practicante')),
            ],
            options={
                'verbose_name': 'Nivel de Habilidad',
                'verbose_name_plural': 'Niveles de Habilidades',
                'ordering': ['-puntaje'],
                'unique_together': {('practicante', 'habilidad')},
            },
        ),
    ]
