# Generated by Django 5.2.6 on 2025-09-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Practicantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HorarioRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_falta', models.ManyToManyField(related_name='faltas', to='Horarios.dia')),
                ('dias_recuperacion', models.ManyToManyField(related_name='recuperaciones', to='Horarios.dia')),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Practicantes.practicante')),
            ],
            options={
                'verbose_name': 'Horario de recuperación',
                'verbose_name_plural': 'Horarios de recuperación',
                'ordering': ['practicante'],
            },
        ),
    ]
