# Generated by Django 5.2.6 on 2025-09-24 18:08

from django.db import migrations


def insertar_datos_iniciales(apps, schema_editor):
    # Obtener los modelos desde apps para evitar errores durante la migración
    Especialidad = apps.get_model('Practicantes', 'Especialidad')
    Dia = apps.get_model('Horarios', 'Dia')
    Habilidad = apps.get_model('Habilidades', 'Habilidad')

    # Insertar especialidades
    especialidades = ['LÍDER', 'SCRUM MASTER', 'PRODUCT OWNER', 'FRONTEND', 'BACKEND']
    for nombre in especialidades:
        Especialidad.objects.get_or_create(nombre=nombre)

    # Insertar días
    dias = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado']
    for nombre in dias:
        Dia.objects.get_or_create(nombre=nombre)

    # Insertar habilidades
    habilidades = ['JavaScript', 'React', 'Figma', 'Python', 'Django', 'Docker', 'MySQL', 'PHP', 'Laravel']
    for nombre in habilidades:
        Habilidad.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('Practicantes', '0001_initial'),
        ('Horarios', '0001_initial'),
        ('Habilidades', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insertar_datos_iniciales),
    ]
